---
- name: EDA | Alertmanager | Playbook reacting to AlertManager Event with ITSM ticket
  hosts: localhost
  tasks:
    - name: Handle new firing alert
      when: alertStatus == "firing"
      block:
        - name: Debug message
          ansible.builtin.debug:
            msg:
              - "The event {{ item.labels.alertName }} just triggered on {{ item.labels.alertTargetHosts }}"
              - "Alert body is: {{ item.labels.alertMessage }}"
          loop: "{{ ansible_eda.event.payload.alerts }}"

        - name: Open ITSM ticket to report incident
          servicenow.itsm.incident:
            instance:
              host: "{{ snow_instance }}"
              username: "{{ snow_username }}"
              password: "{{ snow_password }}"
            caller: "admin"
            state: new
            short_description: "Alert {{ item.labels.alertName }} on host {{ item.labels.alertTargetHosts }}"
            description: |
              The following alert triggered on {{ item.labels.alertTargetHosts }}:
              "{{ item.labels.alertMessage }}"
          register: _incident
          loop: "{{ ansible_eda.event.payload.alerts }}"

        - name: Retrieve incident number
          ansible.builtin.set_fact:
            incident_number: "{{ _incident.results[0].record.number }}"

        - name: Retrieve incident number
          ansible.builtin.set_stats:
            data:
              incident_number: "{{ _incident.results[0].record.number }}"

        - name: Remediating issue to resolve the alert
          ansible.builtin.debug:
            msg: Trying to solve {{ item.labels.alertName }}
          loop: "{{ ansible_eda.event.payload.alerts }}"

    - name: Notify resolution
      when: alertStatus == "resolved"
      block:
        - name: Close ticket
          servicenow.itsm.incident:
            instance:
              host: "{{ snow_instance }}"
              username: "{{ snow_username }}"
              password: "{{ snow_password }}"
            state: resolved
            number: "{{ ticket_number }}"
            close_code: "Solved (Permanently)"
            close_notes: |
              The following alert triggered on {{ item.labels.alertTargetHosts }}:
              "{{ item.labels.alertMessage }}"
              Was resolved with Event Driven Ansible
          loop: "{{ alerts }}"

        - name: Notify resolution
          ansible.builtin.debug:
            msg: "The event {{ item.labels.alertName }} was just resolved by Ansible Event Driven!"
          loop: "{{ alerts }}"
