---
- name: EDA | Insights | Trigger Malware
  hosts: "{{ target_hosts | default('rhel_demo_servers', true) }}"
  become: true
  tasks:
    - name: EDA | Insights | Install yara package
      ansible.builtin.dnf:
        name: yara
        state: present

    - name: EDA | Insights | Ensure malware configuration config exists
      ansible.builtin.file:
        path: /etc/insights-client/malware-detection-config.yml
        mode: "0755"
        state: touch

    - name: EDA | Insights | Configure malware scan
      ansible.builtin.lineinfile:
        path: /etc/insights-client/malware-detection-config.yml
        regexp: "^test_scan"
        line: "test_scan: false"
        state: present
