---
- name: EDA | Insights | Handle malware reporting
  hosts: localhost
  tasks:
    - name: EDA | Insights | Raise SNOW request to report malware detection
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        caller: "admin"
        state: new
        impact: high
        urgency: critical
        short_description: "Alert {{ item.payload.matched_rules }} detected on host {{ item.payload.host_name }}"
        description: |
          The following alert triggered on {{ item.payload.host_name }}:
          "Malware on {{ item.payload.host_name }}: {{ item.payload.matched_rules }}"
      register: _incident
      loop: "{{ insights_malware }}"

    - name: EDA | Insights | Report Incident creation
      ansible.builtin.debug:
        msg: "Incident {{ _incident.results[0].record.number }} created"
