---
- name: EDA | Insights | PermitRootLogin Remediation
  hosts: "{{ target_hosts | default('rhel_demo_servers', true) }}"
  become: true
  tasks:
    - name: EDA | Insights | Fix SSH Root login permissions
      ansible.builtin.lineinfile:
        regexp: "^PermitRootLogin"
        line: "#PermitRootLogin yes"
        state: present
        path: /etc/ssh/sshd_config

    - name: EDA | Insights | Restart SSHD service
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: EDA | Insights | Restart insights-client collection
      ansible.builtin.command: insights-client
