FROM registry.access.redhat.com/ubi9-minimal
RUN microdnf install java-17 python3 gcc python3-devel -y && microdnf clean all && python -m ensurepip --upgrade && pip3 install ansible ansible-rulebook asyncio aiokafka aiohttp aiosignal
ENV JAVA_HOME="/usr/lib/jvm/jre-17"
COPY eda-ansible/* /
RUN ansible-galaxy collection install ansible.eda
#CMD ansible-rulebook -i inventory.yml --rulebook eda-rulebook-multiple-sources.yml --verbose
