---
collections:
  - ansible.controller
  - community.general
  - kubealex.eda
roles:
  - name: role_aap_controller_setup
    src: https://github.com/kubealex/role_aap_controller_setup.git
  - name: role_eda_controller_setup
    src: https://github.com/kubealex/role_eda_controller_setup.git
