---
- name: EDA | Insights | Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002
        token: "{{ insights_integration_token | default('redhatinsightstoken', true) }}"

  rules:
    - name: EDA | Insights | Detect and remediate recommendation event from Insights
      condition: event.payload.event_type == "new-recommendation"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights - Remediate SSH root login"
            organization: Default
            job_args:
              extra_vars:
                insights_recommendation: "{{ event.payload.events.0.payload.rule_id }}"
                target_hosts: "{{ event.payload.context.display_name }}"

    - name: EDA | Insights | Detect and remediate CVE event from Insights
      condition: event.payload.event_type == "new-advisory"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights - Handle Advisories"
            organization: Default
            job_args:
              extra_vars:
                insights_advisories: "{{ event.payload.events }}"
                insights_advisories_context: "{{ event.payload.context }}"
                target_hosts: "{{ event.payload.context.display_name }}"

    - name: EDA | Insights | Detect and handle malware event from Insights
      condition: event.payload.event_type == "detected-malware"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights - Handle Malware"
            organization: Default
            job_args:
              extra_vars:
                insights_malware: "{{ event.payload.events }}"
                insights_malware_context: "{{ event.payload.context }}"
                target_hosts: "{{ event.payload.context.display_name }}"

    - name: EDA | Insights | Simple type report
      condition: event.payload is defined
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights playbook"
            organization: Default
            job_args:
              extra_vars:
                insights_event_type: "{{ event.payload.events.0.payload.event_type }}"
